{"uuid": "60f605e2-7dc9-4c87-a9f3-c3922cd506db", "children": ["aa3cba4e-3890-43b3-a89d-6c8af5a74ce4", "ddb57c19-6ce4-4b22-9ec1-beda4054483c", "9e120770-79d2-4845-ba7c-db6adabbbda2"], "befores": [{"name": "_xunit_setup_class_fixture_TestHead", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up\n    at JWProxy.command$ (C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:238:13)\n    at tryCatch (C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:67:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:315:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:100:21)\n    at GeneratorFunctionPrototype.invoke (C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\babel-runtime\\regenerator\\runtime.js:136:37)\n    at run (C:\\Program Files (x86)\\Appium\\resources\\app\\webpack:\\~\\babel-polyfill\\~\\core-js\\modules\\es6.promise.js:75:1)\n    at C:\\Program Files (x86)\\Appium\\resources\\app\\webpack:\\~\\babel-polyfill\\~\\core-js\\modules\\es6.promise.js:92:1\n    at flush (C:\\Program Files (x86)\\Appium\\resources\\app\\webpack:\\~\\babel-polyfill\\~\\core-js\\modules\\_microtask.js:18:1)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\python.py\", line 854, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\python.py\", line 776, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\file\\xiangmu\\case\\huaxin\\test_chage_head.py\", line 15, in setup_class\n    self.setapp.password_login(self.driver, '17853561185', '123456a')\n  File \"D:\\file\\xiangmu\\case\\huaxin\\york\\set_app.py\", line 65, in password_login\n    self.driver.find_element(by=By.XPATH, value=\"//*[@text='记住密码']\").click()\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 371, in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1664418056441, "stop": 1664418099900}], "start": 1664418056441, "stop": 1664418100113}