INFO     log:set_app.py:193 地址自动获取成功，用例正常！